### ISSUE TITLE
Undefined function 'v2struct'

### ISSUE THREAD

**Issue by chesterlbtan** [noconaway/MLP#3]
I encounter problem after running Start.m

> Undefined function 'v2struct' for input arguments of type 'struct'.
> 
> Error in MLP (line 26)
> v2struct(model) %unpack input params
> 
> Error in Start (line 32)
> result = MLP(model);

**Comment by nolanbconaway** [comment]
Hey! thanks for letting me know about this. Did you add the utils folder to your path? `v2struct` is in there:

https://github.com/nolanbconaway/MLP/blob/master/utils/v2struct.m

Also, fyi,`v2struct` is just a function i found useful on the matlab file exchange [[link](https://www.mathworks.com/examples/matlab/community/20170-v2struct)].

let me know if this info solves your problem!

**Comment by chesterlbtan** [comment]
yes it worked. Thanks for the reply.

I miss it out.
